name: Check-in

env:
  DOTNET_VERSION: '6.0'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_in:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet run --project tests/Skillaz.SecureChat.AcceptanceTests.fsproj